### ISSUE TITLE
Ensure all elements have test IDs for Playwright automation.

### ISSUE THREAD

**Issue by lo5** [h2oai/nitro#27]

**Comment by coolsat** [comment]
Hi @lo5 , this will really help in creating a robust automated suite. Any chance this can go higher up in priority? thanks!

**Comment by lo5** [comment]
This will be released in 0.17.

Note that:
1. `box(name='foo', ...)` is translated to `<element data-name='foo' .../>`, always.
2. `option(name='foo')` is translated to `<element data-name='foo' .../>`, but only where possible.

In general, `data-name='foo'` is set on the _container_, not the element itself, so if you're using query selectors in the test automation framework, use `[data-name='foo'] input` to refer to input elements and `[data-name='foo'] button` to refer to buttons, instead of `input[data-name='foo']` or `button[data-name='foo']`, i.e. look for a child, not self.
