### ISSUE TITLE
hello world example not showing last page

### ISSUE THREAD

**Issue by tfriedel** [h2oai/nitro#62]
**Describe the bug**
The hello world app shows a red popup for a short moment, after entering answers to the first two questions:
Unexpected message id: want p66 got p68 
(numbers change)

**Expected behavior**
A view showing a sentence like  "What a coincidence, {name}, I feel {feel}, too!"

**Actual behavior**
A red popup with "Unexpected message id: " is shown, then the app jumps to the first page and asks for a name again.

**To Reproduce**
I followed the instructions at https://nitro.h2o.ai/install/
Also ran `pip install "h2o-nitro[web]"` because I got " No module named 'h2o_nitro_web'".
Then ran python3 hello.py,
opened the page in  google chrome and clicked submit to the first two prompts, acknowledging the prefilled values.

**Environment (please complete the following information):**
 - Nitro version: 0.11.0
 - Python version: 3.8.5
 - OS and version:  Ubuntu 20.04.4
 - Browser and version: Chrome 103.0.5060.66

**Comment by lo5** [comment]
@tfriedel - Thanks for reporting.

The `unexpected message id` is a bug introduced recently. Already fixed via https://github.com/h2oai/nitro/commit/48ec71519ff3197596fedd56d39c037ae32d902a. A new release will out in 1-2 days.

I'll also correct the pip-install references on the installation page - thanks for catching that. This was a recent change introduced in v0.11.
